# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "Rooster Ranch"
email: jonathan.cochran@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to Rooster Ranch, a serene hobby farm run by our family 
  in Sunbury, Ohio. As caretakers of this little patch of Mother Earth,
  we offer a range of natural, responsibly-raised products. Our offerings 
  include fresh eggs, rabbit meat, seasonal vegetables, and insightful books. 
  Dive into our farm's story, explore our products, and perhaps find the perfect 
  addition to your table or bookshelf.
baseurl: "" # the subpath of your site, e.g. /blog
url: "roosterran.ch" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: JonathanCochran
github_username:  Jonathan-Cochran

# Build settings
#theme: minima
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed
  - jekyll-include-cache

#THEME Configuration
minimal_mistakes_skin: "dark" #"default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
locale: "en-US"
title_separator: "|"
repository: "Jonathan-Cochran/RoosterRanch"

#include additional folders during compilation
include:
  - _data
  - _pages
  
head_scripts:
  - /assets/css/custom.css
#  - https://code.jquery.com/jquery-3.2.1.min.js

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
